//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_1._0.Res.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WpfEntities : DbContext
    {
        public WpfEntities()
            : base("name=WpfEntities")
        {
        }
        private static WpfEntities _context;

        public static WpfEntities GetContext()
        {
            if (_context == null)
                _context = new WpfEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Аккаунты> Аккаунты { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Поступления> Поступления { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
